spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

cloudinary.cloud-name=dbilxb2oe
cloudinary.api-key=791879167651916
cloudinary.api-secret=i7tF1htcBjy1AYApCXcb5u6miAA

app.jwt-secret = f9d0a7d9b8dbe1cb8c3d84e2a7c62ab9f0a72d67c9a81de

app.cors.allowed-origin = http://localhost:3000
app.jwt.expiration-ms = 8640000
app.jwt.secret =jwtSecretkey


spring.jpa.hibernate.ddl-auto=update
