spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver
cloudinary.cloud-name=my_cloud
cloudinary.api-Key=apiKey
cloudinary.api-secret=apiSecret


spring.jpa.hibernate.ddl-auto=update